config/routes.rb
Rails.application.routes.draw do

  get 'recover/recover'

  get 'recover/show'

  root 'home#index'

  get 'checkout/checkout'
  get 'checkout/checkout_payment'
  get 'checkout/checkout_review'
  get 'checkout/check'

  get 'accounts/dashboard'
  get 'accounts/profile'
  post 'accounts/profile'
  post 'accounts/create'
  get 'accounts/address'
  post 'accounts/address'
  get 'accounts/addaddress'
  post 'accounts/addaddress'
  get 'accounts/orders'
  get 'accounts/singleorder'
  get 'accounts/wishlist'
  get 'accounts/warranty'
  resources :accounts

  get 'home' => 'home#index'
  get 'home/product'
  get 'home/index'
  get 'home/cart'
  get 'home/checkout'
  get 'home/review'
  post 'home/review'
  get 'home/payment'
  get 'home/single_product'
  get 'home/stores'
  get 'home/tac'
  get 'home/privacy'
  get 'home/faq'
  get 'home/aboutus'

  get 'signup' =>  'signup#index'
  resources :signup

  get 'signin' => 'signin#index'
  post 'signin' => 'signin#create'
  delete 'logout' => 'signin#destroy'


  get 'recover' =>'recover#index'









end

app/views/layouts/_footer.html.erb
<!-- ==========================
  FOOTER - START
=========================== -->
<footer class="navbar navbar-default">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 col-xs-6">
        <div class="footer-widget footer-widget-contacts">
          <h4>Contacts</h4>
          <ul class="list-unstyled">
            <li><i class="fa fa-envelope"></i> help@fashionclub.com</li>
            <li><i class="fa fa-phone"></i> +114 356 3567</li>
            <li><i class="fa fa-map-marker"></i> MBD Neopolis, Jalandhar<br /><span style="margin-left: 15%;">Punjab 144411</span></li>
            <li class="social">
              <a href="#"><i class="fa fa-facebook"></i></a>
              <a href="#"><i class="fa fa-twitter"></i></a>
              <a href="#"><i class="fa fa-instagram"></i></a>
              <a href="#"><i class="fa fa-linkedin"></i></a>
              <a href="#"><i class="fa fa-tumblr"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3 col-xs-6">
        <div class="footer-widget footer-widget-links">
          <h4>Information</h4>
          <ul class="list-unstyled">
            <li><a href="/home/aboutus">About Us</a></li>
            <li><a href="/home/stores">Our Stores</a></li>
            <li><a href="/home/tac">Terms & Conditions</a></li>
            <li><a href="/home/privacy">Privacy Policy</a></li>
            <li><a href="/home/faq">FAQ</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3 col-xs-6">
        <div class="footer-widget footer-widget-twitter">
          <h4>Customer Views</h4>
          <div id="footer-widget">
            <ul class="list-unstyled reviews" >
              <li>
                <p>fashionClub has all new arrivals before any other store. I love shopping, so I love fashionClub.<span>- Mark Antony</span></p>
              </li>
              <li>
                <p>fashionClub is the new brand name for fashion world. It just does a magic on your shopping experience.<span>- John Hep</span></p>
              </li>
            </ul>

          </div>
        </div>
      </div>
      <div class="col-sm-3 col-xs-6">
        <div class="footer-widget footer-widget-facebook">
          <h4>Facebook Page</h4>
          <ul class="list-unstyled row row-no-padding">
            <li class="col-xs-3"><a href="#"><img src="/assets/images/avatar/avatar_01.jpg"
                                                  class="img-responsive" alt=""></a></li>
            <li class="col-xs-3"><a href="#"><img src="/assets/images/avatar/avatar_02.jpg"
                                                  class="img-responsive" alt=""></a></li>
            <li class="col-xs-3"><a href="#"><img src="/assets/images/avatar/avatar_03.jpg"
                                                  class="img-responsive" alt=""></a></li>
          </ul>
                        <span class="like">45,500 Likes <a href="#" class="btn btn-default btn-sm">
                            <i class="fa fa-thumbs-up"></i>Like</a></span>
          </p>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <div class="row">
        <div class="col-sm-6">
          <p class="copyright">© fashionClub 2016 All right reserved.</p>
        </div>
        <div class="col-sm-6">
          <ul class="list-inline payment-methods">
            <li><i class="fa fa-cc-amex"></i></li>
            <li><i class="fa fa-cc-diners-club"></i></li>
            <li><i class="fa fa-cc-discover"></i></li>
            <li><i class="fa fa-cc-jcb"></i></li>
            <li><i class="fa fa-cc-mastercard"></i></li>
            <li><i class="fa fa-cc-paypal"></i></li>
            <li><i class="fa fa-cc-stripe"></i></li>
            <li><i class="fa fa-cc-visa"></i></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- ==========================
  FOOTER - END
=========================== -->

app/views/layouts/_header.html.erb
<div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>


<!-- ==========================
    HEADER - START
=========================== -->
<div class="top-header hidden-xs">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-inline contacts">
          <li><i class="fa fa-envelope"></i> help@fashionclub.com</li>
          <li><i class="fa fa-phone"></i> +114 356 3567</li>
        </ul>
      </div>
      <div class="col-sm-6 text-right">
        <ul class="list-inline links">
          <li><a href="/home/stores">Our Stores</a></li>
          <li><a href="/home/aboutus">About Us</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<header class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand"><span>fashion</span>Club</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i
      class="fa fa-bars"></i></button>
    </div>
    <div class="navbar-collapse collapse">
      <p class="navbar-text hidden-xs hidden-sm">There is no end to fashion</p>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="/">Home <span><i class="fa fa-home"></i></span></a>
        </li>
        <li class="dropdown megamenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
             data-delay="300" data-close-others="true" id="menu">Shopping
            <span><i class="fa fa-cart-arrow-down"></i></span></a>

          <ul class="dropdown-menu">

            <li class="col-sm-6 col-md-4">
              <ul class="list-unstyled">
                <li class="title">Men</li>
                <li><%= link_to "Casual Shirts", {action: "product" , controller: "home", cat: "men", subcat: "casual_shirts"} %></li>
                <li><a href="/home/product?cat=men&subcat=tshirts">T- Shirts</a> <span class="label label-danger pull-right">Summer Collection</span></li>
                <li><%= link_to "Jeans", {action: "product" , controller: "home", cat: "men", subcat: "jeans"} %></li>
                <li><a href="/home/product?cat=men&subcat=shorts">Shorts</a></li>
                <li><a href="/home/product?cat=men&subcat=sherwani">Sherwani</a></li>
                <li><a href="/home/product?cat=men&subcat=jackets">Jackets  <span class="label label-info pull-right">50% OFF</span></a></li>
                <div id="accessories">
                  <li><a href="#">Accessories </a></li>
                  <div id="hover-content">
                    <li><a href="/home/product?cat=men&subcat=caps">Caps and Hats</a></li>
                    <li><a href="/home/product?cat=men&subcat=belts">Belts</a></li>
                    <li><a href="/home/product?cat=men&subcat=gloves">Gloves</a></li>
                    <li><a href="/home/product?cat=men&subcat=ties">Ties</a></li>
                    <li><a href="/home/product?cat=men&subcat=wallets">Wallets</a></li>
                  </div>
                </div>

              </ul>
            </li>

            <li class="col-sm-6 col-md-4">
              <ul class="list-unstyled">
                <li class="title">Women
                <li><a href="/home/product?cat=women&subcat=tops">Top and Tees</a></li>
                <li><a href="/home/product?cat=women&subcat=jeans">Jeans And Jeggings</a></li>
                <li><a href="/home/product?cat=women&subcat=skirts">Skirts and Shorts <span class="label label-danger pull-right">Summer Collection</span></a></li>
                <li><a href="/home/product?cat=women&subcat=kurtas">Kurta and Suits</a></li>
                <li><a href="/home/product?cat=women&subcat=dresses">Dresses and JumpSuits<span class="label label-info pull-right">30% OFF SALE</span></a></li>
                <li><a href="/home/product?cat=women&subcat=jackets">Jackets</a></li>

                <div id="accessories">
                  <li><a href="#">Accessories >></a></li>
                  <div id="hover-content">
                    <li><a href="/home/product?cat=women&subcat=caps">Caps and Hats</a></li>
                    <li><a href="/home/product?cat=women&subcat=belts">Belts</a></li>
                    <li><a href="/home/product?cat=women&subcat=gloves">Gloves</a></li>
                    <li><a href="/home/product?cat=women&subcat=socks">Socks</a></li>
                    <li><a href="/home/product?cat=women&subcat=jewellery">Jewellery</a> <span class="label label-danger pull-right">New</span></li>
                    <li><a href="/home/product?cat=women&subcat=hairs">Hair Accesories</a></li>
                  </div>
                </div>

              </ul>
            </li>


            <li class="hidden-xs hidden-sm col-md-4">
              <img src="/assets/images/megamenu.png" class="img-responsive" width="305px;" alt="">
            </li>

          </ul>
        </li>
        <li class="dropdown megamenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
             data-delay="300" data-close-others="true">My Account <span><i class="fa fa-user"></i></span></a>
          <ul class="dropdown-menu quick-action">
            <li class="col-sm-12">
              <ul class="list-unstyled text-center">
                <% if !logged_in? %>
                    <li class="title1">You Need To Login</li>
                    <br>
                    <li class="col-sm-6"><%= link_to "Sign in", signin_path, class: "btn btn-primary btn-block visited", style: {color: "white"} %></li>
                    <li class="col-sm-6"><%= link_to "Sign up", signup_path, class: "btn btn-primary btn-block visited", style: {color: "white"} %></li>
                <% else %>
                    <div>
                      <div class="title1">
                        <li style="font-size: 20px;"><%= "#{current_user.first_name} #{current_user.last_name}" %></li>
                        <li class="email"><%= "#{current_user.email}" %></li>
                      </div>
                      <li><a href="/accounts/orders">Orders</a></li>
                      <li><a href="/accounts/wishlist">Wishlist</a></li>
                      <li><a href="/home/cart">Cart</a></li>
                      <li><a href="/accounts/profile">Profile</a></li>
                      <li><%= link_to "Logout", logout_path, method: "delete" %></li>
                    </div>
                <% end %>
              </ul>
            </li>
          </ul>
        </li>
        <% if logged_in? %>
            <%

              cart_items = Cart.where(user_id: current_user.id, order_placed: 0).order('created_at DESC') # id,user_id,product_id,quantity
              product_ids = cart_items.map { |row| row.product_id }#.to_s.remove("[").remove("]")
              #product_data = Product.find_by_sql("SELECT id,images,name,price,discount,quantity FROM `products` WHERE id IN (#{product_ids});") unless product_ids.empty?

              product_data=[]
              cnt=0;
              product_ids.size.times do |i|
              a=Product.find_by(id: product_ids[i])
              product_data << a
              end

              cart_data_header = cart_items.zip product_data unless product_data.nil?
              if !cart_data_header.nil? and !cart_data_header.empty?

            %>



                <!-- CART START -->

                <li class="dropdown navbar-cart hidden-xs">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true"><i class="fa fa-shopping-cart"><span class="badge"> <%= cart_items.size %> </span></i></a>
                  <ul class="dropdown-menu">
                   <%
                     cart_data_header.each do |cart, prod|
                       if cnt==4
                         break
                       end
                     prod.price = prod.price.to_i-((prod.price.to_i*(prod.discount/100.0)).to_i)*cart.quantity.to_i
                    %>

                        <!-- CART ITEM - START -->
                        <li>
                          <div class="row">
                            <div class="col-sm-3">
                              <img src="/assets/images/products/<%= prod.images %>/1.jpg" class="img-responsive" alt="">

                            </div>
                            <div class="col-sm-9">
                              <h4><a href="/home/single_product?id=<%= cart.id %>"><%= prod.name %></a></h4>
                              <p><%= cart.quantity %>x = Rs <%= prod.price.to_i %> <span> ( <%= cart.size.upcase%>) </span></p>
                              <a href="#" class="remove" onclick="deleteItemFromHeader(<%= cart.id %>);"><i class="fa fa-times-circle"></i></a>
                            </div>
                          </div>
                        </li>
                        <!-- CART ITEM - END -->
                        <% cnt+=1 %>
                    <% end %>
                    <li>
                      <div class="row">
                        <div class="col-sm-6">
                          <a href="/home/cart" class="btn btn-primary btn-block">View Cart</a>
                        </div>
                        <div class="col-sm-6">
                          <a href="/home/checkout" class="btn btn-primary btn-block">Checkout</a>
                        </div>
                      </div>
                    </li>
            <% else %>
                <li class="dropdown navbar-cart hidden-xs">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true"><i class="fa fa-shopping-cart"><span class="badge"> 0 </span></i></a>
                  <ul class="dropdown-menu">
                    <li>No items in your cart!</li>
                  </ul>
                </li>
            <% end %>

            </ul>
            </li>
            <!-- CART END -->
        <% end %>

        <!-- <li class="dropdown navbar-search hidden-xs">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                <ul class="dropdown-menu">
                  <li>
                    <form>
                      <div class="input-group input-group-lg">
                        <input type="text" class="form-control" placeholder="Search ...">
                         <span class="input-group-btn">
                          <button class="btn btn-primary" type="button">Search</button>
                         </span>
                      </div>
                    </form>
                  </li>
                </ul>
              </li> -->
      </ul>
    </div>
  </div>
</header>
<!-- ==========================
  HEADER - END
=========================== -->
<script>
  function deleteItemFromHeader(cart_id) {
    $.ajax({
      type: "GET",
      url: "/home/cart",
      data: {
        cart_id: cart_id
      },
      success: function (response) {
        location.reload();
      },
      error: function (e) {
        alert('Some error occurred while deleting item! ');
      }
    });
  }

</script>

app/views/layouts/accounts.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><%= yield(:title) %>fashionClub - There is no end to fashion</title>

  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic&amp;subset=latin,latin-ext'
        rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,900,800' rel='stylesheet'
        type='text/css'>

  <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="../../../../code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/dragtable.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/owl.carousel.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/animate.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/color-switcher.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/custom.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/color/red.css" id="main-color" rel="stylesheet" type="text/css">
  <style>
    .quick-action{
      width: auto;
      margin-left: 70%;
    }
    .reviews>li>p{
      color: #ffeecc;
      opacity: 0.5;
    }
    .reviews>li>p>span{
      color: #f7e1b5;
      font-style: italic;
      float: right;
      margin-top: 1px;
    }

    .signin>a{
      color: darkblue;
    }


    .title1{
      font-size: 25px !important;
      font-weight: bold;
      letter-spacing: -1px;
      color:#555555;
      border-bottom: 1px solid #EEEEEE;
      margin-bottom:5px;
    }

    .email{
      font-weight: normal;
    }
  </style>

  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

  <!-- ==========================
  BREADCRUMB - START
=========================== -->
  <section class="breadcrumb-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <h2>My Account</h2>
          <p><%= @current_view %></p>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb">
            <li><a href="/home/index">Home</a></li>
            <li><a href="/accounts/dashboard">My Account</a></li>
            <li class="active"><%= @current_view %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- ==========================
      BREADCRUMB - END
    =========================== -->


  <%= yield %>


<%= render 'layouts/footer' %>
<!-- ==========================
 JS
=========================== -->
<script src="../../../../code.jquery.com/jquery-latest.min.js"></script>
<script src="../../../../code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/bootstrap-hover-dropdown.min.js"></script>
<script src="/assets/js/SmoothScroll.js"></script>
<script src="/assets/js/jquery.dragtable.js"></script>
<script src="/assets/js/jquery.card.js"></script>
<script src="/assets/js/owl.carousel.min.js"></script>
<script src="/assets/js/jquery.mb.YTPlayer.min.js"></script>
<script src="/assets/js/color-switcher.js"></script>
<script src="/assets/js/custom.js"></script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><%= yield(:title) %>fashionClub - There is no end to fashion</title>

  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic&amp;subset=latin,latin-ext'
        rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,900,800' rel='stylesheet'
        type='text/css'>

  <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="../../../../code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/dragtable.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/owl.carousel.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/animate.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/color-switcher.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/custom.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/color/red.css" id="main-color" rel="stylesheet" type="text/css">
  <style>
    .quick-action{
      width: auto;
      margin-left: 70%;
    }
    .reviews>li>p{
      color: #ffeecc;
      opacity: 0.5;
    }
    .reviews>li>p>span{
      color: #f7e1b5;
      font-style: italic;
      float: right;
      margin-top: 1px;
    }

    .signin>a{
      color: darkblue;
    }


      .title1{
        font-size: 25px !important;
        font-weight: bold;
        letter-spacing: -1px;
        color:#555555;
        border-bottom: 1px solid #EEEEEE;
        margin-bottom:5px;
      }

      .email{
        font-weight: normal;
      }


    #hover-content{

      display: block;
      overflow: hidden;
      margin-left: 100px;
      max-height: 0;
      opacity: 0;
      transition: max-height 1s, opacity 0.5s;
      -webkit-transition: max-height 1s, opacity 0.5s;
    }

      #accessories:hover #hover-content{
        max-height: 500px;
        opacity: 1;

      }

      .visited:visited{
        color: white !important;
      }
  </style>

  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

<% #debug(params) if Rails.env.development? %>

<%= render 'layouts/footer' %>

<!-- ==========================
 JS
=========================== -->
<script src="../../../../code.jquery.com/jquery-latest.min.js"></script>
<script src="../../../../code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/bootstrap-hover-dropdown.min.js"></script>
<script src="/assets/js/SmoothScroll.js"></script>
<script src="/assets/js/jquery.dragtable.js"></script>
<script src="/assets/js/jquery.card.js"></script>
<script src="/assets/js/owl.carousel.min.js"></script>
<script src="/assets/js/jquery.mb.YTPlayer.min.js"></script>
<script src="/assets/js/color-switcher.js"></script>
<script src="/assets/js/custom.js"></script>

</body>
</html>